#!bin/bash
#
# HANA-CI Kernel Build Script || For VPS / Cloud Server / Local
#
# Copyright 2019, Ahmad Thoriq Najahi "Najahiii" <najahiii@outlook.co.id>
# Copyright 2019, alanndz <alanmahmud0@gmail.com>
# Copyright 2021, Dicky Herlambang "Nicklas373" <herlambangdicky5@gmail.com>
# Copyright 2016-2021, HANA-CI Build Project
# SPDX-License-Identifier: GPL-3.0-or-later

# Import separate environment
source "${HOME}/nicklas/scripts/telegram"
source "${HOME}/nicklas/scripts/hash"

# Script Revision = 20210511

# Build Information
#
# Kernel Name
# 0 = CAF (Stock Based Kernel) || 1 = Kizuna || 2 Fusion (Co-operate with @alanndz)
#
# Kernel Scheduler
# 0 = HMP || 1 = EAS
#
# Kernel State
# 0 = BETA || 1 = Stable
#
# Android Version // AVR
# 0 = 10.0 || 1 = 11.0 || 2 = 9.0 - 10.0
#
# Kernel Codename
# 0 = Mido || 1 = Lavender
#
# Kernel Clang Compiler
# 0 = Proton Clang 13 || 1 = AOSP Clang || 2 = SDCLANG 12.0 || 3 = SDCLANG 10.0
#
# Kernel GCC Compiler (Compat VDSO (Extend with Clang)
# 0 = GCC 4.9 (Non-Elf)
#
# Kernel Overclock
# 0 = Non-OC || 1 = OC
#
# Kernel Build Status
# 0 = Dirty / Cache || 1 = Clean
#
# Lavender Cam Patch
# 0 = Old cam || 1 = New cam
#
# Lavender NLMK Patch Disabler
# 0 = Disable || 1 = Enable
#
# Lavender Touchscreen Common
# 0 = Disable || 1 = Enable
#
# Declare Kernel Details
KERNEL_NAME=1
KERNEL_SCHED=1
KERNEL_STATE=0
KERNEL_AND_VER=1
KERNEL_AVR=1
KERNEL_CODENAME=1
KERNEL_CLANG=2
KERNEL_GCC=1
KERNEL_OVERCLOCK=1
KERNEL_CLEAN_BUILD=1
KERNEL_NEW_CAM=0
KERNEL_LAVENDER_TS_COMMON=0

# Environment init
function env_init() {

# Set ARCH
export ARCH=arm64
export SUBARCH=arm64

# Set Build Status
if [ "$KERNEL_CLEAN_BUILD" == "0" ];
	then
		clean="dirty"
elif [ "$KERNEL_CLEAN_BUILD" == "1" ];
	then
		clean="clean"
fi

}

# Mido init
function mido_init() {

# Clone source for specific kernel name
if [ "$KERNEL_NAME" == "0" ];
	then
		# Define Kernel Specific Tag
		KERNEL_CAF_TAG="LA.UM.9.6.2.r1-04600-89xx.0"

		# Define Kernel Specific Environment
		KERNEL_SCHED="EAS"
		KERNEL_BRANCH="lineage-17.1"
		KERNEL_REV="r12"
		KERNEL_REL="CAF"
		KERNEL_RELEASE_NAME="LTS"
		KERNEL_HASH=${CAF_MIDO_HASH}
		ANYKERNEL_BRANCH="caf/mido-4.9"
elif [ "$KERNEL_NAME" == "1" ];
	then
		# Define Kernel Specific Tag
		KERNEL_CAF_TAG="LA.UM.9.6.2.r1-04600-89xx.0"

		# Define Kernel Specific Environment
		KERNEL_SCHED="EAS"
		if [ "$KERNEL_STATE" == "0" ];
			then
				KERNEL_BRANCH="staging/luna"
		elif [ "$KERNEL_STATE" == "1" ];
			then
				KERNEL_BRANCH="kizuna"
		fi
		KERNEL_RELEASE_NAME="シャイノグラフィ || LTS"
		KERNEL_REV="r10"
		KERNEL_REL="Kizuna"
		KERNEL_HASH=${KIZUNA_MIDO_HASH}
		ANYKERNEL_BRANCH="caf/mido-kizuna-4.9"
fi

# Define Global Environment for Mido
IMAGE="${HOME}/kernel/msm-4.9/out/arch/arm64/boot/Image.gz-dtb"
KERNEL="${HOME}/kernel/msm-4.9"
KERNEL_TEMP="${HOME}/nicklas/TEMP"
if [ "$KERNEL_OVERCLOCK" == "1" ];
	then
		KERNEL_CLOCK="OC"
		KERNEL_CLK_STR="Overclock"
		KERNEL_DEVICE="CPU | GPU"
else
	KERNEL_CLOCK=""
	KERNEL_CLK_STR="Default"
	KERNEL_DEVICE=""
fi
CODENAME="mido"
KERNEL_CODE="Mido"
TELEGRAM_DEVICE="Xiaomi Redmi Note 4x"

# Set Build Host
export KBUILD_BUILD_USER=Amana
export KBUILD_BUILD_HOST=Team.Luna

# Define Kernel Release State
if [ "$KERNEL_STATE" == "1" ];
	then
		KERNEL_RELEASE="Stable"
elif [ "$KERNEL_STATE" == "0" ];
	then
		KERNEL_RELEASE="BETA"
fi

# Define Specific Telegram Environment
if [ "$KERNEL_STATE" == "1" ];
	then
		TELEGRAM_GROUP_ID=${telegram_group_official_mido_id}
elif [ "$KERNEL_STATE" == "0" ];
	then
		TELEGRAM_GROUP_ID=${telegram_group_dev_id}
fi
}

# Lavender init
function lave_init() {

# Define Kernel Scheduler
KERNEL_SCHED="EAS"
KERNEL_BRANCH="fusion-nodebug"

# Define Build Host
export KBUILD_BUILD_USER=alanndz-nicklas373
export KBUILD_BUILD_HOST=fusion_lavender-Dev

KERNEL="${HOME}/kernel/msm-4.4"
IMAGE="${HOME}/kernel/msm-4.4/out/arch/arm64/boot/Image.gz-dtb"
ANYKERNEL="${HOME}/nicklas/AnyKernel3"
ANYKERNEL_BRANCH="lavender"
KERNEL_TEMP="${HOME}/nicklas/TEMP"
CODENAME="lavender"
KERNEL_CODE="Lavender"
if [ "$KERNEL_OVERCLOCK" == "1" ];
	then
		KERNEL_CLOCK="OC"
		KERNEL_CLK_STR="Overclock"
		KERNEL_DEVICE="CPU"
elif [ "$KERNEL_OVERCLOCK" == "0" ];
	then
		KERNEL_CLOCK=""
		KERNEL_CLK_STR="Default"
                KERNEL_DEVICE=""
fi
TELEGRAM_DEVICE="Xiaomi Redmi Note 7"
KERNEL_REV="r12"
KERNEL_HASH=${FUSION_LAVENDER_HASH}
KERNEL_CAF_TAG="LA.UM.8.2.r2-04400-sdm660.0"
KERNEL_REL="Fusion"

# Declare Kernel Release State
if [ "$KERNEL_STATE" == "1" ];
	then
		KERNEL_RELEASE="Stable"
		KERNEL_RELEASE_NAME="Water Edge"
		KERNEL_VERSION="r11"
elif [ "$KERNEL_STATE" == "0" ];
	then
		KERNEL_RELEASE="BETA"
		KERNEL_RELEASE_NAME="Unknown"
		KERNEL_VERSION="r12"
fi

TELEGRAM_GROUP_ID=${telegram_group_dev_id}
}

# Additional init environment
function add_init() {

# Declare global additional environment
KERNEL_SUFFIX="Kernel"
KERNEL_DATE="$(date +%Y%m%d-%H%M)"

# Declare Android Version
if [ "$KERNEL_AND_VER" == "0" ];
	then
		KERNEL_ANDROID_VER="9"
		KERNEL_TAG="P"
elif [ "$KERNEL_AND_VER" == "1" ];
	then
		if [ "$KERNEL_AVR" == "0" ];
			then
				KERNEL_ANDROID_VER="10"
				KERNEL_TAG="Q"
		elif [ "$KERNEL_AVR" == "1" ];
			then
				KERNEL_ANDROID_VER="11"
				KERNEL_TAG="R"
		fi
elif [ "$KERNEL_AND_VER" == "2" ];
	then
		KERNEL_ANDROID_VER="9-10"
		KERNEL_TAG="P-Q"
fi

# Declare Telegram File Environment
TELEGRAM_FILENAME="${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-${KERNEL_REV}-${KERNEL_SCHED}-${KERNEL_TAG}-${KERNEL_DATE}.zip"
export TELEGRAM_SUCCESS="CAACAgEAAx0CSp9MtQABBEjFX9VtGvPTMhgokFvqQLFDvYDqbgIAAqkAAyQIgUVzkLgBnPXQ4h4E"
export TELEGRAM_FAIL="CAACAgEAAx0CSp9MtQABBEjCX9Vs9JSeG9aAsei2MzYTIfWdOMMAAsYAA9pAgEVorUReGk7A2h4E"
}

# Cloning Clang
function clang_init() {

if [ "$KERNEL_GCC" == "0" ];
	then
		if [ "$KERNEL_CLANG" == "0" ];
			then
				# Clang environment
				export CLANG_PATH=${HOME}/compiler/proton/bin
				export PATH=${CLANG_PATH}:${PATH}
				export LD_LIBRARY_PATH="${HOME}/compiler/proton/bin/../lib:$PATH"
		fi
elif [ "$KERNEL_GCC" == "1" ];
	then
		if [ "$KERNEL_CLANG" == "1" ];
			then
				# Clang environment
				export CLANG_PATH=${HOME}/compiler/aosp-clang/bin
				export PATH=${CLANG_PATH}:${PATH}
				export LD_LIBRARY_PATH="${HOME}/compiler/aosp-clang/bin/../lib:$PATH"
		elif [ "$KERNEL_CLANG" == "2" ];
			then
				# Clang environment
				export CLANG_PATH=${HOME}/compiler/sdclang-12/bin
				export PATH=${CLANG_PATH}:${PATH}
				export LD_LIBRARY_PATH="${HOME}/compiler/sdclang-12/bin/../lib:$PATH"
		elif [ "$KERNEL_CLANG" == "3" ];
			then
				# Clang environment
				export CLANG_PATH=${HOME}/compiler/sdclang-10/bin
				export PATH=${CLANG_PATH}:${PATH}
				export LD_LIBRARY_PATH="${HOME}/compiler/sdclang-10/bin/../lib:$PATH"
		fi

		# GCC environment
		export CROSS_COMPILE=${HOME}/compiler/gcc_4.9_64/arm64/bin/aarch64-linux-android-
		export CROSS_COMPILE_ARM32=${HOME}/compiler/gcc_4.9/arm/bin/arm-linux-androideabi-
fi
}

# Declare Machine Builder
function builder_init() {
cat /proc/version > ${HOME}/nicklas/builder
TELEGRAM_BUILDER=$(cat ${HOME}/nicklas/builder)
}

# Declare Telegram Bot Aliases
function telegram_init() {
TELEGRAM_KERNEL_VER=$(cat ${KERNEL}/out/.config | grep Linux/arm64 | cut -d " " -f3)
TELEGRAM_UTS_VER=$(cat ${KERNEL}/out/include/generated/compile.h | grep UTS_VERSION | cut -d '"' -f2)
TELEGRAM_COMPILER_NAME=$(cat ${KERNEL}/out/include/generated/compile.h | grep LINUX_COMPILE_BY | cut -d '"' -f2)
TELEGRAM_COMPILER_HOST=$(cat ${KERNEL}/out/include/generated/compile.h | grep LINUX_COMPILE_HOST | cut -d '"' -f2)
TELEGRAM_TOOLCHAIN_VER=$(cat ${KERNEL}/out/include/generated/compile.h | grep LINUX_COMPILER | cut -d '"' -f2)
}

# Telegram Bot Service || Compiling Notification
function bot_template() {
curl -s -X POST https://api.telegram.org/bot${telegram_bot_id}/sendMessage -d chat_id=${TELEGRAM_GROUP_ID} -d "parse_mode=HTML" -d text="$(
	for POST in "${@}";
		do
			echo "${POST}"
		done
	)"
}

# Telegram Bot Service || Compiling Message
function bot_first_compile() {
	builder_init
	bot_template	"<b>|| HANA-CI Build Bot ||</b>" \
			"" \
			"<b>${KERNEL_REL} ${KERNEL_CLOCK} Kernel build Start!</b>" \
			"" \
			"============= Build Information ================" \
			"<b>Release Status :</b><code> ${KERNEL_RELEASE} </code>" \
			"<b>Build Status :</b><code> ${clean} </code>" \
			"<b>Device :</b><code> ${TELEGRAM_DEVICE} </code>" \
			"<b>Android Version :</b><code> ${KERNEL_ANDROID_VER} </code>" \
			"<b>Builder :</b><code> ${TELEGRAM_BUILDER} </code>" \
			"" \
			" =========== Kernel Information ================" \
			"<b>Kernel Scheduler : </b><code> ${KERNEL_SCHED} </code>" \
			"<b>Kernel Clock : </b><code> ${KERNEL_CLK_STR} ${KERNEL_DEVICE} </code>" \
			"<b>Kernel Tag : </b><code> ${KERNEL_CAF_TAG} </code>" \
			"<b>Kernel Branch : </b><code> ${KERNEL_BRANCH} </code>" \
			"<b>Kernel Commit : </b><code> $(git --no-pager log --pretty=format:'"%h - %s (%an)"' -1) </code>"
}

# Telegram bot message || complete compile notification
function bot_complete_compile() {
	builder_init
	telegram_init
	bot_template	"<b>|| HANA-CI Build Bot ||</b>" \
			"" \
			"<b>New ${KERNEL_REL} ${KERNEL_CLOCK} Kernel Build Is Available!</b>" \
			"" \
			"============ Build Information ================" \
			"<b>Build Status :</b><code> ${KERNEL_RELEASE} </code>" \
			"<b>Device :</b><code> ${TELEGRAM_DEVICE} </code>" \
			"<b>Android Version :</b><code> ${KERNEL_ANDROID_VER} </code>" \
   			"<b>Filename :</b><code> ${TELEGRAM_FILENAME}</code>" \
			"<b>Builder :</b><code> ${TELEGRAM_BUILDER} </code>" \
			"" \
			"=========== Kernel Information ================" \
			"<b>Kernel Scheduler : </b><code> ${KERNEL_SCHED} </code>" \
			"<b>Kernel Clock : </b><code> ${KERNEL_CLK_STR} ${KERNEL_DEVICE} </code>" \
			"<b>Kernel Tag : </b><code> ${KERNEL_CAF_TAG} </code>" \
			"<b>Kernel Branch : </b><code> ${KERNEL_BRANCH} </code>" \
			"<b>Kernel Linux Version:</b><code> Linux ${TELEGRAM_KERNEL_VER}</code>" \
			"<b>Kernel Release Ver :</b><code> ${KERNEL_REV} </code>" \
			"<b>Kernel Codename :</b><code> ${KERNEL_RELEASE_NAME} </code>" \
			"<b>Kernel Builder :</b><code> ${TELEGRAM_COMPILER_NAME}@${TELEGRAM_COMPILER_HOST}</code>" \
			"<b>Kernel Toolchain :</b><code> ${TELEGRAM_TOOLCHAIN_VER}</code>" \
			"<b>Kernel Build Date :</b><code> ${TELEGRAM_UTS_VER}</code>" \
			"" \
			"=========== Misc Information ==================" \
			"<b>Kernel Commit :</b><code> $(git --no-pager log --pretty=format:'"%h - %s (%an)"' -1)</code>" \
			"<b>Compile Time :</b><code> $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s)</code>" \
			"" \
			"<b>                         HANA-CI Build Project | 2016-2021                            </b>"
}

# Telegram bot message || success notification
function bot_build_success() {
	bot_template	"<b>|| HANA-CI Build Bot ||</b>" \
			"" \
			"<b>${KERNEL_REL} Kernel build Success!</b>"
}

# Telegram bot message || failed notification
function bot_build_failed() {
	bot_template	"<b>|| HANA-CI Build Bot ||</b>" \
			"" \
			"<b>${KERNEL_REL} ${KERNEL_CLOCK} Kernel build Failed!</b>" \
			"" \
			"<b>Compile Time :</b><code> $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s)</code>"
}

# Telegram Bot Service || Git commit log message
function bot_message() {
	bot_template    "<b>|| HANA-CI Build Bot ||</b>" \
			"" \
			"<b>Temporary Changelog</b>" \
			"" \
			"$(git log ${KERNEL_HASH}^..HEAD --format='%C(auto)%h | %s | Author: %C(green)%aN%Creset | %aD %n')"
}

# Telegram sticker message
function sendStick() {
	curl -s -X POST https://api.telegram.org/bot${telegram_bot_id}/sendSticker -d sticker="${1}" -d chat_id=${TELEGRAM_GROUP_ID} &>/dev/null
}

# Compile Mido Begin
function compile_mido() {
	cd ${KERNEL}
	bot_first_compile

# Cleanup specific changed file while before setup for custom CPU/GPU clock
if [ "$KERNEL_NAME" == "1" ];
	then
		rm localversion
		rm arch/arm64/configs/mido_defconfig
		echo "-キズナ" > localversion
		cp ${HOME}/nicklas/backup/${CODENAME}/mido_defconfig arch/arm64/configs/mido_defconfig
fi

# Changed to specific branch
git checkout ${KERNEL_BRANCH}

if [ "$KERNEL_CLEAN_BUILD" == "1" ];
	then
		make clean && make mrproper
		rm -rvf out
fi
if [ "$KERNEL_NAME" == "0" ];
	then
		rm ${KERNEL}/localversion
		echo "-perf" > ${KERNEL}/localversion
elif [ "$KERNEL_NAME" == "1" ];
	then
		if [ "$KERNEL_OVERCLOCK" == "1" ];
			then
				rm ${KERNEL}/localversion
				echo "-キズナ-OC-r10" > ${KERNEL}/localversion
				sed -i -e 's/# CONFIG_MACH_XIAOMI_C6_OVERCLOCKED is not set/CONFIG_MACH_XIAOMI_C6_OVERCLOCKED=y/g' ${KERNEL}/arch/arm64/configs/mido_defconfig
				sed -i -e 's/CONFIG_MACH_XIAOMI_C6_DEFAULT=y/# CONFIG_MACH_XIAOMI_C6_DEFAULT is not set/g' ${KERNEL}/arch/arm64/configs/mido_defconfig
				sed -i -e 's/# CONFIG_MACH_XIAOMI_C6_GPU_OVERCLOCKED is not set/CONFIG_MACH_XIAOMI_C6_GPU_OVERCLOCKED=y/g' ${KERNEL}/arch/arm64/configs/mido_defconfig
		elif [ "$KERNEL_OVERCLOCK" == "0" ];
			then
				rm ${KERNEL}/localversion
				echo "-キズナ-r10" > ${KERNEL}/localversion
				sed -i -e 's/CONFIG_MACH_XIAOMI_C6_OVERCLOCKED=y/# CONFIG_MACH_XIAOMI_C6_OVERCLOCKED is not set/g' ${KERNEL}/arch/arm64/configs/mido_defconfig
				sed -i -e 's/# CONFIG_MACH_XIAOMI_C6_DEFAULT is not set/CONFIG_MACH_XIAOMI_C6_DEFAULT=y/g' ${KERNEL}/arch/arm64/configs/mido_defconfig
				sed -i -e 's/CONFIG_MACH_XIAOMI_C6_GPU_OVERCLOCKED=y/# CONFIG_MACH_XIAOMI_C6_GPU_OVERCLOCKED is not set/g' ${KERNEL}/arch/arm64/configs/mido_defconfig
		fi
fi
	cat ${KERNEL}/localversion
	START=$(date +"%s")
	make ${CODENAME}_defconfig O=out
if [ "$KERNEL_CLANG" == "0" ];
	then
		CLANG_PATH="${HOME}/compiler/proton/bin/:${PATH}"
elif [ "$KERNEL_CLANG" == "1" ];
	then
		CLANG_PATH="${HOME}/compiler/aosp-clang/bin/:${HOME}/compiler/gcc_4.9_64/arm64/bin/:${HOME}/compiler/gcc_4.9/arm/bin/:${PATH}"
elif [ "$KERNEL_CLANG" == "2" ];
	then
		CLANG_PATH="${HOME}/compiler/sdclang-12/bin/:${HOME}/compiler/gcc_4.9_64/arm64/bin/:${HOME}/compiler/gcc_4.9/arm/bin/:${PATH}"
elif [ "$KERNEL_CLANG" == "3" ];
	then
		CLANG_PATH="${HOME}/compiler/sdclang-10/bin/:${HOME}/compiler/gcc_4.9_64/arm64/bin/:${HOME}/compiler/gcc_4.9/arm/bin/:${PATH}"
fi
if [ "$KERNEL_CLANG" == "0" ] || [ "$KERNEL_CLANG" == "1" ];
	then
		PATH="$CLANG_PATH" \
		make -j$(nproc --all) O=out \
				CC=clang \
				AR=llvm-ar \
				NM=llvm-nm \
				STRIP=llvm-strip \
				OBJCOPY=llvm-objcopy \
				OBJDUMP=llvm-objdump \
				OBJSIZE=llvm-size \
				READELF=llvm-readelf \
				HOSTCC=clang \
				HOSTCXX=clang++ \
				HOSTAR=llvm-ar \
				CLANG_TRIPLE=aarch64-linux-gnu- \
				CROSS_COMPILE=aarch64-linux-gnu- \
				CROSS_COMPILE_ARM32=arm-linux-gnueabi- 2>&1 | tee ${KERNEL_TEMP}/compile.log
elif [ "$KERNEL_CLANG" == "2" ] || [ "$KERNEL_CLANG" == "3" ];
	then
		PATH="$CLANG_PATH" \
		make -j$(nproc --all) O=out \
				CC=clang \
				CROSS_COMPILE=aarch64-linux-gnu- \
				CROSS_COMPILE_ARM32=arm-linux-gnueabi- 2>&1 | tee ${KERNEL_TEMP}/compile.log
fi
	if ! [ -a $IMAGE ];
		then
			echo "kernel not found"
			END=$(date +"%s")
			DIFF=$(($END - $START))
			cd ${KERNEL}
			bot_build_failed
			cd ..
			sendStick "${TELEGRAM_FAIL}"
			curl -F chat_id=${TELEGRAM_GROUP_ID} -F document="@${KERNEL_TEMP}/compile.log"  https://api.telegram.org/bot${telegram_bot_id}/sendDocument
			exit 1
	fi
	END=$(date +"%s")
	DIFF=$(($END - $START))
	cd ${KERNEL}
	bot_build_success
if [ "$KERNEL_STATE" == "0" ];
	then
		bot_message
fi
	cd ..
	sendStick "${TELEGRAM_SUCCESS}"
	cp ${IMAGE} ${HOME}/nicklas/AnyKernel3
	anykernel
	kernel_upload
}

# Compile Lavender Begin
function compile_lave() {
	START=$(date +"%s")
	cd ${KERNEL}
	git checkout ${KERNEL_BRANCH}
	bot_first_compile
if [ "$KERNEL_CLEAN_BUILD" == "1" ];
	then
		make clean && make mrproper
		rm -rvf out
fi
	sed -i -e 's/CONFIG_ANDROID_NLMK=y/# CONFIG_ANDROID_NLMK is not set/g' ${KERNEL}/arch/arm64/configs/lavender_defconfig
if [ "$KERNEL_LAVENDER_TS_COMMON" == "0" ];
	then
		echo "Disable TS Common Nodes"
		sed -i -e 's/CONFIG_TOUCHSCREEN_COMMON=y/# CONFIG_TOUCHSCREEN_COMMON is not set/g' ${KERNEL}/arch/arm64/configs/lavender_defconfig
elif [ "$KERNEL_LAVENDER_TS_COMMON" == "1" ];
	then
		echo "Enable TS Common Nodes"
		sed -i -e 's/# CONFIG_TOUCHSCREEN_COMMON is not set/CONFIG_TOUCHSCREEN_COMMON=y/g' ${KERNEL}/arch/arm64/configs/lavender_defconfig
fi
if [ "$KERNEL_OVERCLOCK" == "0" ];
	then
		echo "Disable CPU Overclock"
		sed -i -e 's/# CONFIG_MACH_XIAOMI_LAVENDER_DEFAULT is not set/CONFIG_MACH_XIAOMI_LAVENDER_DEFAULT=y/g' ${KERNEL}/arch/arm64/configs/lavender_defconfig
		sed -i -e 's/CONFIG_MACH_XIAOMI_LAVENDER_OVERCLOCKED=y/# CONFIG_MACH_XIAOMI_LAVENDER_OVERCLOCKED is not set/g' ${KERNEL}/arch/arm64/configs/lavender_defconfig
elif [ "$KERNEL_OVERCLOCK" == "1" ];
	then
		echo "Enable CPU Overclock"
		sed -i -e 's/CONFIG_MACH_XIAOMI_LAVENDER_DEFAULT=y/# CONFIG_MACH_XIAOMI_LAVENDER_DEFAULT is not set/g' ${KERNEL}/arch/arm64/configs/lavender_defconfig
		sed -i -e 's/# CONFIG_MACH_XIAOMI_LAVENDER_OVERCLOCKED is not set/CONFIG_MACH_XIAOMI_LAVENDER_OVERCLOCKED=y/g' ${KERNEL}/arch/arm64/configs/lavender_defconfig
fi
	make ${CODENAME}_defconfig O=out
if [ "$KERNEL_CLANG" == "0" ];
	then
		CLANG_PATH="${HOME}/compiler/proton/bin/:${PATH}"
elif [ "$KERNEL_CLANG" == "1" ];
	then
		CLANG_PATH="${HOME}/compiler/aosp-clang/bin/:${HOME}/compiler/gcc_4.9_64/arm64/bin/:${HOME}/compiler/gcc_4.9/arm/bin/:${PATH}"
elif [ "$KERNEL_CLANG" == "2" ];
	then
		CLANG_PATH="${HOME}/compiler/sdclang-12/bin/:${HOME}/compiler/gcc_4.9_64/arm64/bin/:${HOME}/compiler/gcc_4.9/arm/bin/:${PATH}"
elif [ "$KERNEL_CLANG" == "3" ];
	then
		CLANG_PATH="${HOME}/compiler/sdclang-10/bin/:${HOME}/compiler/gcc_4.9_64/arm64/bin/:${HOME}/compiler/gcc_4.9/arm/bin/:${PATH}"
fi
	PATH="$CLANG_PATH"
if [ "$KERNEL_CLANG" == "0" ] || [ "$KERNEL_CLANG" == "1" ];
	then
		make -j$(nproc --all) O=out \
					CC=clang \
					AR=llvm-ar \
					NM=llvm-nm \
					STRIP=llvm-strip \
					OBJCOPY=llvm-objcopy \
					OBJDUMP=llvm-objdump \
					OBJSIZE=llvm-size \
					READELF=llvm-readelf \
					HOSTCC=clang \
					HOSTCXX=clang++ \
					HOSTAR=llvm-ar \
					CLANG_TRIPLE=aarch64-linux-gnu- \
					CROSS_COMPILE=aarch64-linux-gnu- \
					CROSS_COMPILE_ARM32=arm-linux-gnueabi- 2>&1 | tee ${KERNEL_TEMP}/compile.log
elif [ "$KERNEL_CLANG" == "2" ] || [ "$KERNEL_CLANG" == "3" ];
	then
		make -j$(nproc --all) O=out \
					CC=clang \
					CROSS_COMPILE=aarch64-linux-gnu- \
					CROSS_COMPILE_ARM32=arm-linux-gnueabi- 2>&1 | tee ${KERNEL_TEMP}/compile.log
fi
	if ! [ -a $IMAGE ];
		then
			echo "kernel not found"
			END=$(date +"%s")
			DIFF=$(($END - $START))
			bot_build_failed
			sendStick "${TELEGRAM_FAIL}"
			curl -F chat_id=${TELEGRAM_GROUP_ID} -F document="@${KERNEL_TEMP}/compile.log"  https://api.telegram.org/bot${telegram_bot_id}/sendDocument
			exit 1
	fi
	END=$(date +"%s")
	DIFF=$(($END - $START))
	cd ${KERNEL}
	bot_build_success
	bot_message
	sendStick "${TELEGRAM_SUCCESS}"
	cd ..
	cp ${IMAGE} ${ANYKERNEL}
	anykernel
	kernel_upload
	if [ "$KERNEL_NEW_CAM" == "0" ];
		then
			echo "Build Done :3"
	elif [ "$KERNEL_NEW_CAM" == "1" ];
		then
			if [ "$NEW_PATCH_STATS" == "0" ];
				then
					init_patch
			elif [ "$NEW_PATCH_STATS" == "1" ];
				then
					echo "Build Done :3"
			fi
	fi
}

# Camera patch
function init_patch() {

cd ${KERNEL}

echo "Enable New Cam Drivers"
sed -i -e 's/# CONFIG_MACH_XIAOMI_LAVENDER_NEW_CAM is not set/CONFIG_MACH_XIAOMI_LAVENDER_NEW_CAM=y/g' ${KERNEL}/arch/arm64/configs/lavender_defconfig

# Declare specified kernel name for pie patch
TELEGRAM_FILENAME="${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-${KERNEL_REV}-${KERNEL_SCHED}-${KERNEL_TAG}-${KERNEL_DATE}-New_CAM.zip"

# Tell if new cam patch already executed
NEW_PATCH_STATS="1"

# Begin init compiling process
compile_lave
}

# AnyKernel
function anykernel() {
	cd ${ANYKERNEL}

	git checkout ${ANYKERNEL_BRANCH}
	make -j4
	if ["$ANYKERNEL_BRANCH" == "caf/mido-4.9" ];
		then
			mv ${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-signed.zip ${KERNEL_TEMP}/${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-${KERNEL_REV}-${KERNEL_SCHED}-${KERNEL_TAG}-${KERNEL_DATE}.zip
	else
		if [ "$KERNEL_OVERCLOCK" == "0" ];
			then
				mv ${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-signed.zip ${KERNEL_TEMP}/${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-${KERNEL_REV}-${KERNEL_SCHED}-${KERNEL_TAG}-${KERNEL_DATE}.zip
		else
			mv ${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-signed.zip ${KERNEL_TEMP}/${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-${KERNEL_CLOCK}-${KERNEL_REV}-${KERNEL_SCHED}-${KERNEL_TAG}-${KERNEL_DATE}.zip
		fi
	fi
}

# Upload Kernel
function kernel_upload() {
	cd ${KERNEL}
	bot_complete_compile
	if [ "$KERNEL_STATE" == "0" ];
		then
			# Upload kernel file
			echo "Upload kernel..."

			if [ "$KERNEL_OVERCLOCK" == "0" ];
				then
					curl -F chat_id=${TELEGRAM_GROUP_ID} -F document="@${KERNEL_TEMP}/${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-${KERNEL_REV}-${KERNEL_SCHED}-${KERNEL_TAG}-${KERNEL_DATE}.zip"  https://api.telegram.org/bot${telegram_bot_id}/sendDocument
			else
				curl -F chat_id=${TELEGRAM_GROUP_ID} -F document="@${KERNEL_TEMP}/${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-${KERNEL_CLOCK}-${KERNEL_REV}-${KERNEL_SCHED}-${KERNEL_TAG}-${KERNEL_DATE}.zip"  https://api.telegram.org/bot${telegram_bot_id}/sendDocument
			fi

				echo "Upload log..."
				curl -F chat_id=${TELEGRAM_GROUP_ID} -F document="@${KERNEL_TEMP}/compile.log"  https://api.telegram.org/bot${telegram_bot_id}/sendDocument

			echo "Upload git log.."
			git log ${KERNEL_HASH}^..HEAD --format="format:%C(auto)%h | %s | Author: %C(green)%aN%Creset | %cD" > ${KERNEL_TEMP}/git.log
			curl -F chat_id=${TELEGRAM_GROUP_ID} -F document="@${KERNEL_TEMP}/git.log"  https://api.telegram.org/bot${telegram_bot_id}/sendDocument

	elif [ "$KERNEL_STATE" == "1" ];
		then
			# Upload kernel file
			echo "Upload kernel file..."

			if [ "$KERNEL_OVERCLOCK" == "0" ];
				then
					curl -F chat_id=${TELEGRAM_GROUP_ID} -F document="@${KERNEL_TEMP}/${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-${KERNEL_REV}-${KERNEL_SCHED}-${KERNEL_TAG}-${KERNEL_DATE}.zip"  https://api.telegram.org/bot${telegram_bot_id}/sendDocument
			else
				curl -F chat_id=${TELEGRAM_GROUP_ID} -F document="@${KERNEL_TEMP}/${KERNEL_REL}-${KERNEL_SUFFIX}-${KERNEL_CODE}-${KERNEL_CLOCK}-${KERNEL_REV}-${KERNEL_SCHED}-${KERNEL_TAG}-${KERNEL_DATE}.zip"  https://api.telegram.org/bot${telegram_bot_id}/sendDocument
			fi
	fi
}

function cleanup() {
	rm -rvf ${ANYKERNEL}/Image.gz-dtb
	rm -rvf ${KERNEL_TEMP}/*.zip
	rm -rvf ${KERNEL_TEMP}/*.log
}

function run() {
if [ "$KERNEL_CODENAME" == "1" ];
	then
		echo "LAVENDER"

		env_init
		lave_init
		clang_init
		add_init
		if [ "$KERNEL_NEW_CAM" == "1" ];
			then
				# Tell if new cam patch need to executed
				NEW_PATCH_STATS="0"

				# Compile
				compile_lave
		elif [ "$KERNEL_NEW_CAM" == "0" ];
			then
				compile_lave
		fi
elif [ "$KERNEL_CODENAME" == "0" ];
	then
		echo "MIDO"

		env_init
		mido_init
		clang_init
		add_init
		compile_mido
fi

cleanup
}

# Running
run
