#!/bin/bash

# Set Clang Environment
CLANG_DIR="${WORK_DIR}/tools"
export CLANG_PATH=${HOME}/tools/${CLANG_NAME}/bin
export PATH=${CLANG_PATH}:${PATH}
export LD_LIBRARY_PATH="${HOME}/tools/${CLANG_NAME}/bin/../lib:$PATH"
