#!/bin/bash

# Set Build Host

# Set Kernel Specific Environment (Fusion-Lavender)
ANYKERNEL_BRANCH="lavender"
CODENAME="lavender"
KERNEL_CODE="Lavender"
KERNEL_BRANCH="fusion-nodebug"
KERNEL_REV="r13-UNRELEASED"
KERNEL_HASH=${FUSION_LAVENDER_HASH}
KERNEL_CAF_TAG="LA.UM.8.2.r2-04900-sdm660.0"
KERNEL_REL="Fusion"
KERNEL_ALT="fusion"
TELEGRAM_DEVICE="Xiaomi Redmi Note 7"
