#!/bin/bash

# Specific Kernel Environment (Kizuna Kernel)
KERNEL_BRANCH_DEV="staging/hoshizora"
KERNEL_BRANCH_REL="kizuna"
KERNEL_RELEASE_NAME=" キズナ♪ || LTS "
KERNEL_REV="r10"
KERNEL_REL="Kizuna"
KERNEL_ALT="kizuna"
KERNEL_HASH=${KIZUNA_MIDO_HASH}
ANYKERNEL_BRANCH="caf/mido-kizuna-4.9"
