#!/bin/bash

# Specific Kernel Environment (Kizuna Kernel)
KERNEL_BRANCH_DEV="staging/upstream-kizuna"
KERNEL_BRANCH_REL="staging/upstream-kizuna"
KERNEL_RELEASE_NAME=" ~ FUTURITY SMILE ~ || LTS"
KERNEL_REV="r11"
KERNEL_REL="Kizuna"
KERNEL_ALT="kizuna"
KERNEL_HASH=${KIZUNA_MIDO_HASH}
ANYKERNEL_BRANCH="caf/mido-kizuna-4.9"
